version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: '14'
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Running build...
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - package.json
    - yarn.lock
    - 'dist/**/*'
